const CONSTANT_TYPES = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    SHOW_HIDE_DROP: "SHOW_HIDE_DROP",
    SET_CARTITEMS: "SET_CARTITEMS",
    DELETE_CARTITEM: 'DELETE_CARTITEM',
    DECREASE_QUANTITY: 'DECREASE_QUANTITY',
    SET_SHOP_DATA: 'SET_SHOP_DATA',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    SIGN_OUT_START: 'SIGN_OUT_START',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    CLEAR_CART_ITEMS: 'CLEAR_CART_ITEMS',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE'

}

export default CONSTANT_TYPES;